name: windows-quic
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: [ windows-latest ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure and build
      run: |
          mkdir build 
          cd build
          cmake -G "Visual Studio 17 2022" -DNNG_ENABLE_QUIC=ON -DQUIC_BUILD_SHARED=OFF ..
          cmake --build .

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure

